Systango_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', admin.site.urls, name='datas'),
    path('', views.home, name='home'),
    path('register/', include('registration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('database_1/', include('database_1.urls')),
    path('database_2/', include('database_2.urls')),
    path('database_3/', include('database_3.urls')),
    path('database_4/', include('database_4.urls')),
    path('database_5/', include('database_5.urls')),
    path('database/', include('databases.urls')),

]

urlpatterns += staticfiles_urlpatterns()
admin.site.site_header = "Systango Project"
admin.site.site_title = "Systango Project"
admin.site.index_title = "Database Control Panel"

database_3/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_data, name='view_3'),
    path('delete/<int:id>', views.delete, name='delete_3'),
    path('update/<int:id>', views.update_data, name='update_3'),
    path('updated/<int:id>', views.updated, name='updated_3'),
    path('save/', views.save_data, name='save_3'),
]

databases/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.view, name='view_data'),

]

database_3/models.py
from django.db import models


class Product3(models.Model):
    user = models.CharField(max_length=100)
    product = models.CharField(max_length=255)
    price = models.IntegerField()
    quantity = models.IntegerField()

    class Meta:
        app_label = 'database_3'

    def __str__(self):
        return self.product

database_3/views.py
from django.shortcuts import render, redirect
from .models import Product3



def view_data(request):
    obj = Product3.objects.all()
    db = 3
    return render(request, 'database_3/view data_3.html', {'result': obj, 'db': db})


def save_data(request):
    user = request.user.username
    product = request.POST['product']
    price = request.POST['price']
    quantity = request.POST['quantity']
    obj = Product3(user=user, product=product, price=price, quantity=quantity)
    obj.save()
    return redirect('view_3')




def delete(request, id):
    obj = Product3.objects.get(id=id)
    obj.delete()
    return redirect('view_3')




def update_data(request, id):
    obj = Product3.objects.all()
    single = Product3.objects.get(id=id)
    db = 3
    return render(request, 'database_3/update data_3.html', {'result': obj, 'single': single, 'db': db})


def updated(request, id):
    obj = Product3.objects.get(id=id)
    obj.product = request.POST['product']
    obj.price = request.POST['price']
    obj.quantity = request.POST['quantity']
    obj.save()
    return redirect('view_3')

templates/database_3/update data_3.html
{% extends 'base.html' %}

{% block head %}
    <title>Database - {{ db }}</title>
{% endblock %}

{% block body %}
    <div class="container">
    <div class="row justify-content-center">
    <div class="col-6">

        <form action="{% url 'updated_3' single.id %}" method="post">
            {% csrf_token %}
            <br>
            <div style="text-align: center;"><h2>Update Data to Database {{ db }}</h2></div>
            <br>


            <div id="div_id_product" class="form-group"> <label for="id_product" class="col-form-label  requiredField">
                Product<span class="asteriskField">*</span> </label> <div class=""> <input type="text" name="product" value="{{ single.product }}" maxlength="255" class="textinput textInput form-control" required id="id_product"> </div> </div> <div id="div_id_price" class="form-group"> <label for="id_price" class="col-form-label  requiredField">
                Price<span class="asteriskField">*</span> </label> <div class=""> <input type="number" name="price" value="{{ single.price }}" class="numberinput form-control" required id="id_price"> </div> </div> <div id="div_id_quantity" class="form-group"> <label for="id_quantity" class="col-form-label  requiredField">
                Quantity<span class="asteriskField">*</span> </label> <div class=""> <input type="number" name="quantity" value="{{ single.quantity }}" class="numberinput form-control" required id="id_quantity"> </div> </div>
            <br>
            <div style="text-align: center;"><button class="btn btn-lg btn-outline-dark">Update Data</button></div>
            <br><br>
        </form>
    </div>
    </div>
    <table class="table table-hover">
        <thead class="table-dark">
        <tr>
            <th>Id</th>
            <th>Product Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>User</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
            {% for x in result %}
                <tr>
                <td><b>{{ x.id }}</b></td>
                <td>{{ x.product }}</td>
                <td>{{ x.price }}</td>
                <td><b>{{ x.user.capitalize }}</b></td>
                <td>{{ x.quantity }}</td>
                <td><a href="{% url 'update_3' x.id %}" class="btn col-5 btn-warning">Edit</a> <a href="{% url 'delete_3' x.id %}" class="btn col-5 btn-danger">Delete</a></td>

                </tr>
            {% endfor %}

        </tbody>
    </table>

    </div>
{% endblock %}

templates/database_3/view data_3.html
{% extends 'base.html' %}

{% block head %}
    <title>Database - {{ db }}</title>
{% endblock %}

{% block body %}
    <div class="container">
    <div class="row justify-content-center">
    <div class="col-6">
        {% load crispy_forms_tags %}
        <form action="{% url 'save_3' %}" method="post">
            {% csrf_token %}
            <br><div style="text-align: center;">
            <h2>Insert Data to Database {{ db }}</h2></div>
            <br>

            <div id="div_id_product" class="form-group">
                <label for="id_product" class="col-form-label  requiredField">Product<span class="asteriskField">*</span></label>
                <div class=""> <input type="text" name="product"  maxlength="255" class="textinput textInput form-control" required id="id_product"> </div> </div>

            <div id="div_id_price" class="form-group">
                <label for="id_price" class="col-form-label  requiredField">Price<span class="asteriskField">*</span></label>
                <div class=""> <input type="number" name="price"  class="numberinput form-control" required id="id_price"> </div> </div>
            <div id="div_id_quantity" class="form-group">
                <label for="id_quantity" class="col-form-label  requiredField">Quantity<span class="asteriskField">*</span></label>
                <div class=""><input type="number" name="quantity" class="numberinput form-control" required id="id_quantity"> </div> </div>
            <br>
            <div style="text-align: center;"><button class="btn btn-lg btn-outline-dark">Insert Data</button></div>
            <br><br>
        </form>
    </div>
    </div>
    <table class="table table-hover">
        <thead class="table-dark">
        <tr>
            <th>Id</th>
            <th>Product Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>User</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
            {% for x in result %}
                <tr>
                <td><b>{{ x.id }}</b></td>
                <td>{{ x.product }}</td>
                <td>{{ x.price }}</td>
                <td>{{ x.quantity }}</td>
                <td><b>{{ x.user.capitalize }}</b></td>
                <td><a href="{% url 'update_3' x.id %}" class="btn col-5 btn-warning">Edit</a> <a href="{% url 'delete_3' x.id %}" class="btn col-5 btn-danger">Delete</a></td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
    {{ a }}
    </div>
{% endblock %}